import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";
import { Toaster } from "@/components/ui/sonner";
import LandingPageNav from "@/components/LandingPageNav";
import { Marquee } from "@/components/magicui/marquee";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "DiaMate",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="id" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="w-full mb-5 bg-yellow-100 text-yellow-900 px-4 text-sm md:text-base text-center flex items-center justify-center gap-5 border-b border-yellow-300">
            <Marquee>
              <strong className="font-medium">Perhatian:</strong> Hasil dari
              DiaMate bersifat prediktif awal dan bukan diagnosis medis.
            </Marquee>
          </div>

          {/* Navbar */}
          <LandingPageNav />
          {children}
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
